# Generated by Django 5.2.8 on 2026-01-15 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktywnosc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj_aktywnosci', models.CharField(choices=[('bieganie', 'Bieganie'), ('jazda_rowerem', 'Jazda rowerem'), ('plywanie', 'Pływanie'), ('silownia', 'Siłownia'), ('inna', 'Inna')], max_length=50)),
                ('czas_trwania_minuty', models.PositiveIntegerField()),
                ('data', models.DateField()),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('dawka', models.CharField(max_length=100)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pomiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('cisnienie_skurczowe', models.PositiveIntegerField(blank=True, null=True)),
                ('cisnienie_rozkurczowe', models.PositiveIntegerField(blank=True, null=True)),
                ('tetno', models.PositiveIntegerField(blank=True, null=True)),
                ('pomiar_cukru', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilUzytkownika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plec', models.IntegerField(choices=[(1, 'Mężczyzna'), (2, 'Kobieta'), (3, 'Inna')], default=3)),
                ('telefon', models.CharField(blank=True, max_length=9)),
                ('data_urodzenia', models.DateField(blank=True, null=True)),
                ('wzrost_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('waga_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('uzytkownik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wizyty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie_nazwisko_lekarza', models.CharField(max_length=100)),
                ('specjalizacja', models.CharField(max_length=100)),
                ('data_wizyty', models.DateTimeField()),
                ('lokalizacja', models.CharField(max_length=200)),
                ('notatki', models.TextField(blank=True)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
