# Generated by Django 5.2.8 on 2026-01-16 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthhub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aktywnosc',
            options={'ordering': ['-data'], 'verbose_name': 'Aktywność', 'verbose_name_plural': 'Aktywności'},
        ),
        migrations.AlterModelOptions(
            name='leki',
            options={'ordering': ['nazwa'], 'verbose_name': 'Lek', 'verbose_name_plural': 'Leki'},
        ),
        migrations.AlterModelOptions(
            name='pomiary',
            options={'ordering': ['-data'], 'verbose_name': 'Pomiar', 'verbose_name_plural': 'Pomiary'},
        ),
        migrations.AlterModelOptions(
            name='wizyty',
            options={'ordering': ['-data_wizyty'], 'verbose_name': 'Wizyta', 'verbose_name_plural': 'Wizyty'},
        ),
        migrations.AddIndex(
            model_name='aktywnosc',
            index=models.Index(fields=['uzytkownik', 'data'], name='healthhub_a_uzytkow_8c2082_idx'),
        ),
        migrations.AddIndex(
            model_name='pomiary',
            index=models.Index(fields=['uzytkownik', 'data'], name='healthhub_p_uzytkow_7536f0_idx'),
        ),
        migrations.AddIndex(
            model_name='wizyty',
            index=models.Index(fields=['uzytkownik', 'data_wizyty'], name='healthhub_w_uzytkow_282d6c_idx'),
        ),
    ]
