# Generated by Django 5.2.8 on 2026-01-17 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthhub', '0002_alter_aktywnosc_options_alter_leki_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lokalizacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=150)),
                ('adres', models.CharField(max_length=200)),
                ('miasto', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nazwa', 'miasto'],
            },
        ),
        migrations.CreateModel(
            name='TerminWizyty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie_nazwisko_lekarza', models.CharField(max_length=100)),
                ('specjalizacja', models.CharField(max_length=100)),
                ('data_wizyty', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Termin wizyty',
                'verbose_name_plural': 'Terminy wizyt',
                'ordering': ['data_wizyty'],
            },
        ),
        migrations.RenameModel(
            old_name='Leki',
            new_name='Lek',
        ),
        migrations.RenameModel(
            old_name='Pomiary',
            new_name='Pomiar',
        ),
        migrations.RemoveField(
            model_name='wizyty',
            name='uzytkownik',
        ),
        migrations.RenameIndex(
            model_name='pomiar',
            new_name='healthhub_p_uzytkow_e99654_idx',
            old_name='healthhub_p_uzytkow_7536f0_idx',
        ),
        migrations.AddField(
            model_name='terminwizyty',
            name='lokalizacja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='healthhub.lokalizacja'),
        ),
        migrations.AddField(
            model_name='terminwizyty',
            name='uzytkownik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Wizyty',
        ),
        migrations.AddIndex(
            model_name='terminwizyty',
            index=models.Index(fields=['uzytkownik', 'data_wizyty'], name='healthhub_t_uzytkow_fb30ca_idx'),
        ),
        migrations.AddIndex(
            model_name='terminwizyty',
            index=models.Index(fields=['data_wizyty'], name='healthhub_t_data_wi_e5cb33_idx'),
        ),
        migrations.AddConstraint(
            model_name='terminwizyty',
            constraint=models.UniqueConstraint(fields=('imie_nazwisko_lekarza', 'data_wizyty', 'lokalizacja'), name='unique_termin'),
        ),
    ]
