# Generated by Django 5.2.8 on 2026-01-22 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthhub', '0003_lokalizacja_terminwizyty_rename_leki_lek_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lokalizacja',
            options={'ordering': ['nazwa', 'miasto'], 'verbose_name': 'Lokalizacja', 'verbose_name_plural': 'Lokalizacje'},
        ),
        migrations.AlterModelOptions(
            name='profiluzytkownika',
            options={'verbose_name': 'Profil użytkownika', 'verbose_name_plural': 'Profile użytkowników'},
        ),
    ]
